POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
"email": "usuario@upf.br",
"password": "abc123"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
"name": "usuario",
"email": "usuario@upf.br",
"passwordHash": "abc123"
}

###
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXN1YXJpb0B1cGYuYnIiLCJuYW1lIjoidXN1YXJpbyIsImlhdCI6MTc4OTk1MDQ1MSwiZXhwIjoxNzkwMDM2ODUxfQ.sRZQ9cWfEFap2-e00D2w70znX6baXylV2Txej6KZQ_w