@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiam9hb0BlbWFpbC5jb20iLCJuYW1lIjoiSm_Do28iLCJpYXQiOjE3OTAyMDQyMzgsImV4cCI6MTc5MDI5MDYzOH0.bOqg50uKEcvkBtVaqdi2XeJk3SZfwp4bck63cpK3yhM


POST {{baseUrl}}/auth/login
Content-Type: application/json

{
"email": "usuario@upf.br",
"password": "abc123"
}

###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
"name": "usuario",
"email": "usuario@upf.br",
"passwordHash": "abc123"
}

###
POST {{baseUrl}}/auth/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "João",
  "email": "joao@email.com",
  "password": "123456",
  "role": "PHYSIOTHERAPIST"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
"email": "joao@email.com",
"password": "123456"
}

###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Maria",
  "email": "maria@teste.com",
  "password": "123456",
  "role": "PATIENT"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
"email": "maria@teste.com",
"password": "123456"
}

###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "testee",
  "email": "teste@teste.com",
  "password": "123456"
}

###
POST {{baseUrl}}/login
Content-Type: application/json

{
"email": "teste@teste.com",
"password": "123456"
}

###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "testew",
  "email": "testew@teste.com",
  "password": "123456"
}

