@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXN1YXJpb0B1cGYuYnIiLCJuYW1lIjoidXN1YXJpbyIsImlhdCI6MTc5MTE2MDc5NywiZXhwIjoxNzkxMjQ3MTk3fQ.hnxT_9tPPpRAcxEntNAb9aymnkah3WN5SfF_4gZ57kc

### Todos
GET {{baseUrl}}/physiotherapists
Authorization: Bearer {{token}}

### Cidade
GET {{baseUrl}}/physiotherapists?city=Marau
Authorization: Bearer {{token}}

### Especialidade
GET {{baseUrl}}/physiotherapists?specialtyId=1
Authorization: Bearer {{token}}

### Presencial
GET {{baseUrl}}/physiotherapists?serviceMode=IN_PERSON
Authorization: Bearer {{token}}

### Online
GET {{baseUrl}}/physiotherapists?serviceMode=ONLINE
Authorization: Bearer {{token}}

### Todos os filtros
GET {{baseUrl}}/physiotherapists?city=Marau&specialtyId=1&serviceMode=IN_PERSON
Authorization: Bearer {{token}}

### Deve dar 400
GET {{baseUrl}}/physiotherapists?specialtyId=abc
Authorization: Bearer {{token}}

### Deve dar 400
GET {{baseUrl}}/physiotherapists?serviceMode=TESTE
Authorization: Bearer {{token}}