@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidXN1YXJpb0B1cGYuYnIiLCJuYW1lIjoidXN1YXJpbyIsImlhdCI6MTc5MTA3MzI4MiwiZXhwIjoxNzkxMTU5NjgyfQ.h9KRxs5F5bAksR4qB6IzgewAZy5szZ1aOzjQGwZW-ZU

### Todos os fisioterapeutas
GET {{baseUrl}}/physiotherapists
Authorization: Bearer {{token}}

### Buscar fisioterapeuta pelo id
GET {{baseUrl}}/physiotherapists/1
Authorization: Bearer {{token}}

### Filtrar por cidade
GET {{baseUrl}}/physiotherapists?city=Marau
Authorization: Bearer {{token}}

### Filtrar por especialidade
GET {{baseUrl}}/physiotherapists?specialtyId=1
Authorization: Bearer {{token}}

### Filtrar por modalidade
GET {{baseUrl}}/physiotherapists?serviceMode=IN_PERSON
Authorization: Bearer {{token}}

### Cidade + especialidade
GET {{baseUrl}}/physiotherapists?city=Marau&specialtyId=1
Authorization: Bearer {{token}}

### Cidade + modalidade
GET {{baseUrl}}/physiotherapists?city=Marau&serviceMode=ONLINE
Authorization: Bearer {{token}}

### Todos os filtros juntos
GET {{baseUrl}}/physiotherapists?city=Marau&specialtyId=1&serviceMode=BOTH
Authorization: Bearer {{token}}