@baseUrl = http://localhost:3000/api
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiam9hb0BlbWFpbC5jb20iLCJuYW1lIjoiSm_Do28iLCJpYXQiOjE3OTA2MjQ3NTEsImV4cCI6MTc5MDcxMTE1MX0.mDbCB2jCZ_fpn-CWx9Xl71rz4Cvy2Xjm1ZEBTqwZvuI


### Criar horário disponível
POST {{baseUrl}}/schedules
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "dateTime": "2026-10-25T14:00:00Z"
}

###
GET {{baseUrl}}/schedules?physiotherapistId=1
Authorization: Bearer {{token}}


