@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiam9hb0BlbWFpbC5jb20iLCJuYW1lIjoiSm_Do28iLCJpYXQiOjE3OTAyMDQyMzgsImV4cCI6MTc5MDI5MDYzOH0.bOqg50uKEcvkBtVaqdi2XeJk3SZfwp4bck63cpK3yhM

POST {{baseUrl}}/specialties
Authorization: Bearer {{token}}

{
  "name": "teste",
  "description": "Tratamento de lesões relacionadas ao esporte",
  "icon": "sports"
}

###
GET http://localhost:3000/api/specialties
Authorization: Bearer {{token}}